{% set name = "spechomo" %}
{% set version = "0.10.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spechomo-{{ version }}.tar.gz
  sha256: ad0b15b5d885419265cc1d663b92b2cd8359787cfd394c4de59f07ac44549961

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-git
  run:
    - dill
    - geoarray >=0.15.0
    - matplotlib-base
    - natsort
    - nested_dict
    - numpy <2
    - pandas
    - pyrsr >=0.5.0
    - python >=3.6
    - pyyaml
    - scikit-learn >=0.23.2,<1
    - scipy <1.11
    - seaborn
    - specclassify >=0.3.0
    - tabulate
    - tqdm

test:
  imports:
    - spechomo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/geomultisens/spechomo
  summary: Spectral homogenization of multispectral satellite data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
