{% set name = "spechomo" %}
{% set version = "0.10.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spechomo-{{ version }}.tar.gz
  sha256: 0c3f4139e293150923ffeff9b4a8109a2e73ed36d4d7d7467ddd21747b9d255c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-git
  run:
    - dill
    - geoarray >=0.15.0
    - matplotlib-base
    - natsort
    - nested_dict
    - numpy
    - pandas
    - pyrsr >=0.5.0
    - python >=3.6
    - pyyaml
    - scikit-learn >=0.23.2
    - scipy
    - seaborn
    - specclassify >=0.3.0
    - tabulate
    - tqdm

test:
  imports:
    - spechomo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/geomultisens/spechomo
  summary: Spectral homogenization of multispectral satellite data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
